export default {
    products:[
        {
        _id:'1',
        name:'Slim Shirt',
        category:'shirts',
        image:'/images/d1.jpg',
        price:60,
        brand:'Nike',
        rating:4.5,
        numReviews:10,
        countInStock:6,
    },
    {
        _id:'2',
        name:'Fit Shirt',
        category:'shirts',
        image:'/images/d2.jpg',
        price:50,
        brand:'Nikee',
        rating:4.2,
        numReviews:9,
        countInStock:6,
    },
    {
        _id:'3',
        name:'Best Pants',
        category:'pants',
        image:'/images/d3.webp',
        price:70,
        brand:'Nike',
        rating:4.1,
        numReviews:10,
        countInStock:6,
    },
    {
        _id:'4',
        name:'Best Pants',
        category:'pants',
        image:'/images/d4.jpg',
        price:70,
        brand:'Nike',
        rating:4.1,
        numReviews:10,
        countInStock:6,
    },
    {
        _id:'5',
        name:'Slim Shirt',
        category:'shirts',
        image:'/images/d5.jpg',
        price:60,
        brand:'Nike',
        rating:4.1,
        numReviews:25,
        countInStock:6,
    },
    {
        _id:'6',
        name:'Best Pants',
        category:'pants',
        image:'/images/d7.jpeg',
        price:60,
        brand:'Nike',
        rating:4.1,
        numReviews:25,
        countInStock:2,
    },
]
}

